In [9]:
import pandas as pd

# 读取数据
data = pd.read_csv('data/sales.csv', usecols = ['订单号', '产品类别', '产品名称', '销售数量', '单价'])   # usecols 指定读取的列
data

# 数据处理
data['销售金额'] = data['销售数量'] * data['单价']
data


# 写入数据
data.to_csv('data/sales.csv', index = False)  # index = False 表示不保存索引列

# 数据查看 --> head, tail, describe, info, shape, columns

data.head(10)   # 查看前10行数据
data.tail(10)   # 查看后10行数据
data.describe()  # 数据描述
data.info()   # 数据信息（列名，列数，行数，数据类型，内存使用情况）
data.shape    # 数据形状
data.columns  # 数据列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
 5   销售金额    1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价', '销售金额'], dtype='object')

In [19]:
# 数据选择
data = pd.read_csv('data/sales.csv', usecols = ['订单号', '产品类别', '产品名称', '销售数量', '单价'])
data[['订单号', '产品类别', '产品名称', '销售数量', '单价']]


# 选择列
data['产品类别']   # 单列
data[['产品类别', '产品名称', '销售数量']]  # 多列
data.产品名称

# 选择行
data.loc[0:5, ['订单号', '产品类别', '产品名称', '销售数量', '单价']]   # 语法：loc[行索引, 列索引],含结束位置--> 基于索引选择，并非基于行号选择

data.iloc[0:5]   # 语法：iloc[行索引, 列索引],不含结束位--> 基于行号选择，并非基于索引选择

          订单号  产品类别  产品名称  销售数量   单价
0  6805677496  家居用品    枕头    10  199
1  5857234132    食品    海苔     5   29
2  5888085059  电子产品  智能音箱     5  399
3  6823473137    食品    面包     3   29
4  6801664364    食品    薯片     2   19

In [28]:
# 数据过滤
data = pd.read_csv('data/sales.csv', usecols = ['订单号', '产品类别', '产品名称', '销售数量', '单价'])
data

# 1.获取销售数量大于等于10 的订单数据
data[data['销售数量'] >= 10]

# 2.获取产品类别为食品 或者 图书的订单数据
data[data['产品类别'].isin(['食品', '图书'])]   #isin() 函数 --> 判断是否在列表中

# 3.单价在100-200之间的订单数据-->默认包含边界   # inclusive = True5
data[data['单价'].between(100, 200)]

# 4.获取销售数量 >= 8， 并且单价 >= 100 的订单数据
data[(data['销售数量'] >= 8) & (data['单价'] >= 100)]

# 5.获取产品类别为 服装/食品， 销售数量在 5~10 之间的订单数据
data[data['产品类别'].isin(['服装','食品']) & data['销售数量'].between(5, 10)]

            订单号 产品类别 产品名称  销售数量   单价
1    5857234132   食品   海苔     5   29
6    6857752388   服装   袜子     7  -29
7    6898807429   服装   T恤     6  199
10   5808071569   食品  矿泉水     9   29
19   5852807025   服装   毛衣    10  399
..          ...  ...  ...   ...  ...
988  6845708709   服装   衬衫     7  299
993  6870828210   服装   内衣     8   89
994  5860722276   服装   外套     6  599
998  6876456690   食品   果汁     7   39
999  6842608338   食品   蜂蜜     5   89

[242 rows x 5 columns]

In [41]:
# 配置项，用于展示所有数据
data = pd.set_option('display.max_rows', None)
data